# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WowforgeCli < Formula
  desc "Easily add and update addons for your World of Warcraft installation"
  homepage "https://github.com/m-triassi/wowforge-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.2.0/wowforge-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "0ca47b61eeb8639f06b7f3dc4cee579fa2b59158c0640e6b5a1c95f10cb9a432"

      def install
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.2.0/wowforge-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "6fae56181a01cf8585880c446abe17abce15d82fabc9f8852e2a4a4a011c5a90"

      def install
        bin.install "wowforge-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.2.0/wowforge-cli_1.2.0_linux_arm64.tar.gz"
      sha256 "f6123b393278ca4009685393ba4343c4e118ac4b77cd66e3e32e3e43dc472826"

      def install
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.2.0/wowforge-cli_1.2.0_linux_amd64.tar.gz"
      sha256 "1fe54911bc7c33f7347ff0a83f34b7c9e31462af8f031717f8f5e42f9473470e"

      def install
        bin.install "wowforge-cli"
      end
    end
  end
end
