# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WowforgeCli < Formula
  desc "Easily add and update addons for your World of Warcraft installation"
  homepage "https://github.com/m-triassi/wowforge-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.3.0/wowforge-cli_1.3.0_darwin_amd64.tar.gz"
      sha256 "2f815d9acdc42dca06069fface29137bdd854f4d97b39bd4d60cb485b4d6c98e"

      define_method(:install) do
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.3.0/wowforge-cli_1.3.0_darwin_arm64.tar.gz"
      sha256 "f7c87666302feec34dd7981d534b9251eebf65d36780519ca8b9b29733c784e4"

      define_method(:install) do
        bin.install "wowforge-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.3.0/wowforge-cli_1.3.0_linux_amd64.tar.gz"
      sha256 "a46d9fbb8bd19b42dd7ebdcc48794ad8b6579c1668baa80a1902750b73edef0c"
      define_method(:install) do
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.3.0/wowforge-cli_1.3.0_linux_arm64.tar.gz"
      sha256 "782fe8fbc8fa41a1d2a9c137d18242dd016d8cf4cdb50e002920d56db1a7c5af"
      define_method(:install) do
        bin.install "wowforge-cli"
      end
    end
  end
end
