# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WowforgeCli < Formula
  desc "Easily add and update addons for your World of Warcraft installation"
  homepage "https://github.com/m-triassi/wowforge-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.0.0/wowforge-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "ccd68f5326c0a14d56088394258a3ffc66e24c8bba74134820ef1bbf7d7cf891"

      def install
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.0.0/wowforge-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "3f399233064a76b50673687e03c593fda5e8ff334f7bdd085874b884fbc09625"

      def install
        bin.install "wowforge-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.0.0/wowforge-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "3591a24ea2f58349abf1080285a1039357b0e53d4121c98c2d80a86dbdcc55ea"

      def install
        bin.install "wowforge-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/m-triassi/wowforge-cli/releases/download/v1.0.0/wowforge-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "c1bf21310afa9dcd5bec84e6bfc3c273654e5504e30370c511902138b34c76d0"

      def install
        bin.install "wowforge-cli"
      end
    end
  end
end
